namespace Neovolve.Configuration.DependencyInjection.Generator;

using System.Collections.Immutable;
using System.Text;

/// <summary>
///     The <see cref="AccessorSourceEmitter" /> class emits the generated source that registers strongly typed
///     configuration property accessors with the runtime registry through a module initializer.
/// </summary>
internal static class AccessorSourceEmitter
{
    private const string AccessorType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.ConfigPropertyAccessor";

    private const string RegistryType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.GeneratedConfigRegistry";

    public static string Emit(ImmutableArray<ConfigTypeModel> types, bool hasModuleInitializer)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (hasModuleInitializer == false)
        {
            EmitModuleInitializerPolyfill(builder);
        }

        builder.AppendLine("namespace Neovolve.Configuration.DependencyInjection.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class GeneratedConfigBinders");
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Initialize()");
        builder.AppendLine("        {");

        foreach (var type in types)
        {
            EmitTypeRegistration(builder, type);
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitModuleInitializerPolyfill(StringBuilder builder)
    {
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
        builder.AppendLine("    internal sealed class ModuleInitializerAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitTypeRegistration(StringBuilder builder, ConfigTypeModel type)
    {
        builder.Append("            ").Append(RegistryType).Append(".RegisterProperties(typeof(")
            .Append(type.FullyQualifiedName).AppendLine("),");
        builder.Append("                new ").Append(AccessorType).AppendLine("[]");
        builder.AppendLine("                {");

        foreach (var property in type.Properties)
        {
            EmitAccessor(builder, type.FullyQualifiedName, property);
        }

        builder.AppendLine("                });");
    }

    private static void EmitAccessor(StringBuilder builder, string typeName, ConfigPropertyModel property)
    {
        var canWrite = property.CanWrite ? "true" : "false";
        var isValueType = property.IsValueType ? "true" : "false";

        builder.Append("                    new ").Append(AccessorType).Append('(')
            .Append('"').Append(property.Name).Append("\", ")
            .Append(canWrite).Append(", ")
            .Append(isValueType).AppendLine(",");

        // Getter delegate: read the property and return it boxed as object.
        builder.Append("                        static instance => ((").Append(typeName).Append(")instance).")
            .Append(property.Name).AppendLine(",");

        if (property.CanWrite)
        {
            // Setter delegate: cast the boxed value back to the property type and assign it.
            builder.Append("                        static (instance, value) => ((").Append(typeName)
                .Append(")instance).").Append(property.Name).Append(" = (")
                .Append(property.TypeFullyQualifiedName).AppendLine(")value!),");
        }
        else
        {
            builder.AppendLine("                        null),");
        }
    }
}
