namespace Neovolve.Configuration.DependencyInjection.Generator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

/// <summary>
///     The <see cref="ConfigSourceEmitter" /> class emits the generated source that registers strongly typed configuration
///     property accessors and graph registrars with the runtime registry through a module initializer.
/// </summary>
internal static class ConfigSourceEmitter
{
    private const string ApplierInterfaceType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.IConfigValueApplier";

    private const string ConfigurationType = "global::Microsoft.Extensions.Configuration.IConfiguration";

    private const string RegistrarInterfaceType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.IConfigGraphRegistrar";

    private const string RegistryType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.GeneratedConfigRegistry";

    private const string ServiceCollectionType =
        "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    private const string SupportType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.GeneratedConfigSupport";

    private const string UpdateContextType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.IConfigUpdateContext";

    public static string Emit(ImmutableArray<RootModel> roots, ImmutableArray<ConfigTypeModel> extraAccessorTypes,
        bool hasModuleInitializer)
    {
        var distinctTypes = new Dictionary<string, ConfigTypeModel>(StringComparer.Ordinal);

        foreach (var root in roots)
        {
            foreach (var configType in root.ConfigTypes)
            {
                // Value types are registered as one-time snapshots and are never hot reloaded, so they have no
                // property accessors (and a struct property setter cannot be emitted - it would mutate an
                // unboxed copy).
                if (configType.IsValueType)
                {
                    continue;
                }

                distinctTypes[configType.FullyQualifiedName] = configType;
            }
        }

        foreach (var configType in extraAccessorTypes)
        {
            if (configType.IsValueType)
            {
                continue;
            }

            distinctTypes[configType.FullyQualifiedName] = configType;
        }

        var orderedTypes = distinctTypes.Values
            .OrderBy(static configType => configType.FullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

        var orderedRoots = roots
            .OrderBy(static root => root.RootTypeFullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (hasModuleInitializer == false)
        {
            EmitModuleInitializerPolyfill(builder);
        }

        builder.AppendLine("namespace Neovolve.Configuration.DependencyInjection.Generated");
        builder.AppendLine("{");

        foreach (var root in orderedRoots)
        {
            EmitRegistrar(builder, root);
        }

        if (orderedTypes.Length > 0)
        {
            // The appliers and reporters copy and compare strongly typed property values; nullability annotations on
            // those properties are not relevant and would otherwise require per-property suppression, so they are
            // emitted with nullable analysis disabled.
            builder.AppendLine("#nullable disable");
            builder.AppendLine();

            foreach (var type in orderedTypes)
            {
                EmitReporterClass(builder, type);
            }

            foreach (var type in orderedTypes)
            {
                if (type.IsReportOnly)
                {
                    // Report-only types are complex collection elements used for nested logging only; they have a
                    // reporter but no applier and are not registered.
                    continue;
                }

                EmitApplierClass(builder, type);
            }

            builder.AppendLine("#nullable restore");
            builder.AppendLine();
        }

        builder.AppendLine("    internal static class GeneratedConfigBinders");
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Initialize()");
        builder.AppendLine("        {");

        foreach (var type in orderedTypes)
        {
            if (type.IsReportOnly)
            {
                continue;
            }

            EmitApplierRegistration(builder, type);
        }

        foreach (var root in orderedRoots)
        {
            builder.Append("            ").Append(RegistryType).Append(".RegisterGraph(typeof(")
                .Append(root.RootTypeFullyQualifiedName).Append("), new ")
                .Append(RegistrarName(root.RootTypeFullyQualifiedName)).AppendLine("());");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitApplierClass(StringBuilder builder, ConfigTypeModel type)
    {
        var applierName = ApplierName(type.FullyQualifiedName);

        builder.Append("    internal sealed class ").Append(applierName).Append(" : ")
            .Append(ApplierInterfaceType).Append('<').Append(type.FullyQualifiedName).AppendLine(">");
        builder.AppendLine("    {");
        builder.Append("        public bool Apply(").Append(type.FullyQualifiedName).Append(" injected, ")
            .Append(type.FullyQualifiedName).Append(" updated, ").Append(UpdateContextType).AppendLine(" context)");
        builder.AppendLine("        {");
        builder.AppendLine("            var changed = false;");

        foreach (var property in type.Properties)
        {
            EmitApplyProperty(builder, property);
        }

        builder.AppendLine("            return changed;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitApplyProperty(StringBuilder builder, ConfigPropertyModel property)
    {
        if (property.CanWrite == false)
        {
            // A read only property is never copied; the context applies the configured read only logging policy.
            var isValueType = property.IsValueType ? "true" : "false";

            builder.Append("            context.ReportReadOnly(\"").Append(property.Name).Append("\", ")
                .Append(isValueType).AppendLine(");");

            return;
        }

        if (property.ChangeKind == PropertyChangeKind.ChildConfig)
        {
            // A child configuration type is assigned and, in summary mode, logged independently by its own applier. In
            // deep mode the parent walks it to log nested property changes.
            var reporter = ReporterName(property.TypeFullyQualifiedName);

            builder.AppendLine("            {");
            builder.Append("                ").Append(property.TypeFullyQualifiedName).AppendLine(" previous = default;");
            builder.Append("                ").Append(property.TypeFullyQualifiedName).AppendLine(" current = default;");
            builder.AppendLine("                var copied = false;");
            builder.AppendLine("                try");
            builder.AppendLine("                {");
            builder.Append("                    previous = injected.").Append(property.Name).AppendLine(";");
            builder.Append("                    current = updated.").Append(property.Name).AppendLine(";");
            builder.Append("                    injected.").Append(property.Name).AppendLine(" = current;");
            builder.AppendLine("                    copied = true;");
            builder.AppendLine("                }");
            builder.AppendLine("                catch (global::System.Exception ex)");
            builder.AppendLine("                {");
            builder.Append("                    context.ReportCopyFailure(\"").Append(property.Name)
                .AppendLine("\", ex);");
            builder.AppendLine("                }");
            builder.AppendLine("                if (copied && context.LogNestedChanges && context.IsChangeLoggingEnabled)");
            builder.AppendLine("                {");
            builder.Append("                    changed |= ").Append(reporter).Append(".Report(\"")
                .Append(property.Name).AppendLine("\", previous, current, context);");
            builder.AppendLine("                }");
            builder.AppendLine("            }");

            return;
        }

        // A writable property is copied directly. The get, set and change report are wrapped per property so that a
        // single faulty member cannot stop the rest of the configuration from updating.
        builder.AppendLine("            {");
        builder.Append("                ").Append(property.TypeFullyQualifiedName).AppendLine(" previous = default;");
        builder.Append("                ").Append(property.TypeFullyQualifiedName).AppendLine(" current = default;");
        builder.AppendLine("                var copied = false;");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.Append("                    previous = injected.").Append(property.Name).AppendLine(";");
        builder.Append("                    current = updated.").Append(property.Name).AppendLine(";");
        builder.Append("                    injected.").Append(property.Name).AppendLine(" = current;");
        builder.AppendLine("                    copied = true;");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (global::System.Exception ex)");
        builder.AppendLine("                {");
        builder.Append("                    context.ReportCopyFailure(\"").Append(property.Name).AppendLine("\", ex);");
        builder.AppendLine("                }");
        builder.AppendLine("                if (copied && context.IsChangeLoggingEnabled)");
        builder.AppendLine("                {");

        if (property.ChangeKind == PropertyChangeKind.ScalarList)
        {
            builder.Append("                    changed |= context.ReportValues(\"").Append(property.Name)
                .AppendLine("\", previous, current);");
        }
        else if (property.ChangeKind == PropertyChangeKind.ComplexList)
        {
            var reporter = ReporterName(property.ElementTypeFullyQualifiedName!);

            builder.Append("                    changed |= context.ReportCount(\"").Append(property.Name)
                .AppendLine("\", previous, current);");
            builder.AppendLine(
                "                    if (context.LogNestedChanges && previous != null && current != null && previous.Count == current.Count)");
            builder.AppendLine("                    {");
            builder.AppendLine("                        for (var index = 0; index < previous.Count; index++)");
            builder.AppendLine("                        {");
            builder.Append("                            changed |= ").Append(reporter).Append(".Report(\"")
                .Append(property.Name).Append("[\" + index + \"]\", previous[index], current[index], context);")
                .AppendLine();
            builder.AppendLine("                        }");
            builder.AppendLine("                    }");
        }
        else if (property.ChangeKind == PropertyChangeKind.Countable)
        {
            builder.Append("                    changed |= context.ReportCount(\"").Append(property.Name)
                .AppendLine("\", previous, current);");
        }
        else
        {
            builder.Append("                    changed |= context.ReportValue(\"").Append(property.Name)
                .AppendLine("\", previous, current);");
        }

        builder.AppendLine("                }");
        builder.AppendLine("            }");
    }

    private static void EmitReporterClass(StringBuilder builder, ConfigTypeModel type)
    {
        var reporterName = ReporterName(type.FullyQualifiedName);

        builder.Append("    internal static class ").Append(reporterName).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        public static bool Report(string prefix, ").Append(type.FullyQualifiedName)
            .Append(" previous, ").Append(type.FullyQualifiedName).Append(" updated, ").Append(UpdateContextType)
            .AppendLine(" context)");
        builder.AppendLine("        {");
        builder.AppendLine("            var changed = false;");
        builder.AppendLine("            if (previous == null || updated == null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return changed;");
        builder.AppendLine("            }");
        builder.AppendLine("            try");
        builder.AppendLine("            {");

        foreach (var property in type.Properties)
        {
            EmitReportProperty(builder, property);
        }

        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.Exception ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                context.ReportCopyFailure(prefix, ex);");
        builder.AppendLine("            }");
        builder.AppendLine("            return changed;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitReportProperty(StringBuilder builder, ConfigPropertyModel property)
    {
        // Reporters only describe writable property changes; read only properties are reported by the owning type's
        // own applier at the top level.
        if (property.CanWrite == false)
        {
            return;
        }

        var path = "prefix + \"." + property.Name + "\"";

        if (property.ChangeKind == PropertyChangeKind.ChildConfig)
        {
            var reporter = ReporterName(property.TypeFullyQualifiedName);

            builder.Append("                changed |= ").Append(reporter).Append(".Report(").Append(path)
                .Append(", previous.").Append(property.Name).Append(", updated.").Append(property.Name)
                .AppendLine(", context);");

            return;
        }

        if (property.ChangeKind == PropertyChangeKind.ScalarList)
        {
            builder.Append("                changed |= context.ReportValues(").Append(path).Append(", previous.")
                .Append(property.Name).Append(", updated.").Append(property.Name).AppendLine(");");

            return;
        }

        if (property.ChangeKind == PropertyChangeKind.ComplexList)
        {
            var reporter = ReporterName(property.ElementTypeFullyQualifiedName!);

            builder.AppendLine("                {");
            builder.Append("                    var nestedPrevious = previous.").Append(property.Name).AppendLine(";");
            builder.Append("                    var nestedCurrent = updated.").Append(property.Name).AppendLine(";");
            builder.Append("                    changed |= context.ReportCount(").Append(path)
                .AppendLine(", nestedPrevious, nestedCurrent);");
            builder.AppendLine(
                "                    if (nestedPrevious != null && nestedCurrent != null && nestedPrevious.Count == nestedCurrent.Count)");
            builder.AppendLine("                    {");
            builder.AppendLine("                        for (var index = 0; index < nestedPrevious.Count; index++)");
            builder.AppendLine("                        {");
            builder.Append("                            changed |= ").Append(reporter).Append(".Report(").Append(path)
                .AppendLine(" + \"[\" + index + \"]\", nestedPrevious[index], nestedCurrent[index], context);");
            builder.AppendLine("                        }");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");

            return;
        }

        if (property.ChangeKind == PropertyChangeKind.Countable)
        {
            builder.Append("                changed |= context.ReportCount(").Append(path).Append(", previous.")
                .Append(property.Name).Append(", updated.").Append(property.Name).AppendLine(");");

            return;
        }

        builder.Append("                changed |= context.ReportValue(").Append(path).Append(", previous.")
            .Append(property.Name).Append(", updated.").Append(property.Name).AppendLine(");");
    }

    private static void EmitApplierRegistration(StringBuilder builder, ConfigTypeModel type)
    {
        builder.Append("            ").Append(RegistryType).Append(".RegisterApplier(typeof(")
            .Append(type.FullyQualifiedName).Append("), new ").Append(ApplierName(type.FullyQualifiedName))
            .AppendLine("());");
    }

    private static void EmitModuleInitializerPolyfill(StringBuilder builder)
    {
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine(
            "    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
        builder.AppendLine("    internal sealed class ModuleInitializerAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitRegistrar(StringBuilder builder, RootModel root)
    {
        var registrarName = RegistrarName(root.RootTypeFullyQualifiedName);

        builder.Append("    internal sealed class ").Append(registrarName).Append(" : ")
            .Append(RegistrarInterfaceType).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        public void Register(").Append(ServiceCollectionType).Append(" services, ")
            .Append(ConfigurationType).AppendLine(" configuration)");
        builder.AppendLine("        {");

        builder.Append("            var root = ").Append(SupportType).Append(".RegisterRoot<")
            .Append(root.RootTypeFullyQualifiedName).AppendLine(">(services, configuration);");

        foreach (var interfaceName in root.RootInterfaceFullyQualifiedNames)
        {
            builder.Append("            ").Append(SupportType).Append(".RegisterRootInterface<")
                .Append(root.RootTypeFullyQualifiedName).Append(", ").Append(interfaceName)
                .AppendLine(">(services, root);");
        }

        var structIndex = 0;

        foreach (var registration in root.Registrations)
        {
            if (registration.IsValueType)
            {
                // A struct cannot use the options infrastructure, so it is registered as a one-time snapshot and
                // its interfaces resolve to the same boxed instance.
                var local = "structValue" + structIndex;
                structIndex++;

                builder.Append("            var ").Append(local).Append(" = ").Append(SupportType)
                    .Append(".RegisterConfigStruct<").Append(registration.TypeFullyQualifiedName)
                    .Append(">(services, configuration.GetSection(\"").Append(registration.SectionPath)
                    .AppendLine("\"));");

                foreach (var interfaceName in registration.InterfaceFullyQualifiedNames)
                {
                    builder.Append("            ").Append(SupportType).Append(".RegisterConfigStructInterface<")
                        .Append(interfaceName).Append(">(services, ").Append(local).AppendLine(");");
                }

                continue;
            }

            builder.Append("            ").Append(SupportType).Append(".RegisterConfigType<")
                .Append(registration.TypeFullyQualifiedName).Append(">(services, configuration.GetSection(\"")
                .Append(registration.SectionPath).AppendLine("\"));");

            foreach (var interfaceName in registration.InterfaceFullyQualifiedNames)
            {
                builder.Append("            ").Append(SupportType).Append(".RegisterConfigInterfaceType<")
                    .Append(registration.TypeFullyQualifiedName).Append(", ").Append(interfaceName)
                    .AppendLine(">(services);");
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string ApplierName(string typeFullyQualifiedName)
    {
        return SanitizeIdentifier(typeFullyQualifiedName, "_Applier");
    }

    private static string ReporterName(string typeFullyQualifiedName)
    {
        return SanitizeIdentifier(typeFullyQualifiedName, "_Reporter");
    }

    private static string RegistrarName(string rootTypeFullyQualifiedName)
    {
        return SanitizeIdentifier(rootTypeFullyQualifiedName, "_Registrar");
    }

    private static string SanitizeIdentifier(string typeFullyQualifiedName, string suffix)
    {
        var builder = new StringBuilder(typeFullyQualifiedName.Length + suffix.Length);

        foreach (var character in typeFullyQualifiedName)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.Append(suffix).ToString();
    }
}
