namespace Neovolve.Configuration.DependencyInjection.Generator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

/// <summary>
///     The <see cref="ConfigSourceEmitter" /> class emits the generated source that registers strongly typed configuration
///     property accessors and graph registrars with the runtime registry through a module initializer.
/// </summary>
internal static class ConfigSourceEmitter
{
    private const string AccessorType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.ConfigPropertyAccessor";

    private const string ConfigurationType = "global::Microsoft.Extensions.Configuration.IConfiguration";

    private const string RegistrarInterfaceType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.IConfigGraphRegistrar";

    private const string RegistryType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.GeneratedConfigRegistry";

    private const string ServiceCollectionType =
        "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    private const string SupportType =
        "global::Neovolve.Configuration.DependencyInjection.Generated.GeneratedConfigSupport";

    public static string Emit(ImmutableArray<RootModel> roots, ImmutableArray<ConfigTypeModel> extraAccessorTypes,
        bool hasModuleInitializer)
    {
        var distinctTypes = new Dictionary<string, ConfigTypeModel>(StringComparer.Ordinal);

        foreach (var root in roots)
        {
            foreach (var configType in root.ConfigTypes)
            {
                // Value types are registered as one-time snapshots and are never hot reloaded, so they have no
                // property accessors (and a struct property setter cannot be emitted - it would mutate an
                // unboxed copy).
                if (configType.IsValueType)
                {
                    continue;
                }

                distinctTypes[configType.FullyQualifiedName] = configType;
            }
        }

        foreach (var configType in extraAccessorTypes)
        {
            if (configType.IsValueType)
            {
                continue;
            }

            distinctTypes[configType.FullyQualifiedName] = configType;
        }

        var orderedTypes = distinctTypes.Values
            .OrderBy(static configType => configType.FullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

        var orderedRoots = roots
            .OrderBy(static root => root.RootTypeFullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (hasModuleInitializer == false)
        {
            EmitModuleInitializerPolyfill(builder);
        }

        builder.AppendLine("namespace Neovolve.Configuration.DependencyInjection.Generated");
        builder.AppendLine("{");

        foreach (var root in orderedRoots)
        {
            EmitRegistrar(builder, root);
        }

        builder.AppendLine("    internal static class GeneratedConfigBinders");
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Initialize()");
        builder.AppendLine("        {");

        foreach (var type in orderedTypes)
        {
            EmitTypeRegistration(builder, type);
        }

        foreach (var root in orderedRoots)
        {
            builder.Append("            ").Append(RegistryType).Append(".RegisterGraph(typeof(")
                .Append(root.RootTypeFullyQualifiedName).Append("), new ")
                .Append(RegistrarName(root.RootTypeFullyQualifiedName)).AppendLine("());");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitAccessor(StringBuilder builder, string typeName, ConfigPropertyModel property)
    {
        var canWrite = property.CanWrite ? "true" : "false";
        var isValueType = property.IsValueType ? "true" : "false";

        builder.Append("                    new ").Append(AccessorType).Append('(')
            .Append('"').Append(property.Name).Append("\", ")
            .Append(canWrite).Append(", ")
            .Append(isValueType).AppendLine(",");

        // Getter delegate: read the property and return it boxed as object.
        builder.Append("                        static instance => ((").Append(typeName).Append(")instance).")
            .Append(property.Name).AppendLine(",");

        if (property.CanWrite)
        {
            // Setter delegate: cast the boxed value back to the property type and assign it.
            builder.Append("                        static (instance, value) => ((").Append(typeName)
                .Append(")instance).").Append(property.Name).Append(" = (")
                .Append(property.TypeFullyQualifiedName).AppendLine(")value!),");
        }
        else
        {
            builder.AppendLine("                        null),");
        }
    }

    private static void EmitModuleInitializerPolyfill(StringBuilder builder)
    {
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine(
            "    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
        builder.AppendLine("    internal sealed class ModuleInitializerAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitRegistrar(StringBuilder builder, RootModel root)
    {
        var registrarName = RegistrarName(root.RootTypeFullyQualifiedName);

        builder.Append("    internal sealed class ").Append(registrarName).Append(" : ")
            .Append(RegistrarInterfaceType).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        public void Register(").Append(ServiceCollectionType).Append(" services, ")
            .Append(ConfigurationType).AppendLine(" configuration)");
        builder.AppendLine("        {");

        builder.Append("            var root = ").Append(SupportType).Append(".RegisterRoot<")
            .Append(root.RootTypeFullyQualifiedName).AppendLine(">(services, configuration);");

        foreach (var interfaceName in root.RootInterfaceFullyQualifiedNames)
        {
            builder.Append("            ").Append(SupportType).Append(".RegisterRootInterface<")
                .Append(root.RootTypeFullyQualifiedName).Append(", ").Append(interfaceName)
                .AppendLine(">(services, root);");
        }

        var structIndex = 0;

        foreach (var registration in root.Registrations)
        {
            if (registration.IsValueType)
            {
                // A struct cannot use the options infrastructure, so it is registered as a one-time snapshot and
                // its interfaces resolve to the same boxed instance.
                var local = "structValue" + structIndex;
                structIndex++;

                builder.Append("            var ").Append(local).Append(" = ").Append(SupportType)
                    .Append(".RegisterConfigStruct<").Append(registration.TypeFullyQualifiedName)
                    .Append(">(services, configuration.GetSection(\"").Append(registration.SectionPath)
                    .AppendLine("\"));");

                foreach (var interfaceName in registration.InterfaceFullyQualifiedNames)
                {
                    builder.Append("            ").Append(SupportType).Append(".RegisterConfigStructInterface<")
                        .Append(interfaceName).Append(">(services, ").Append(local).AppendLine(");");
                }

                continue;
            }

            builder.Append("            ").Append(SupportType).Append(".RegisterConfigType<")
                .Append(registration.TypeFullyQualifiedName).Append(">(services, configuration.GetSection(\"")
                .Append(registration.SectionPath).AppendLine("\"));");

            foreach (var interfaceName in registration.InterfaceFullyQualifiedNames)
            {
                builder.Append("            ").Append(SupportType).Append(".RegisterConfigInterfaceType<")
                    .Append(registration.TypeFullyQualifiedName).Append(", ").Append(interfaceName)
                    .AppendLine(">(services);");
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitTypeRegistration(StringBuilder builder, ConfigTypeModel type)
    {
        builder.Append("            ").Append(RegistryType).Append(".RegisterProperties(typeof(")
            .Append(type.FullyQualifiedName).AppendLine("),");
        builder.Append("                new ").Append(AccessorType).AppendLine("[]");
        builder.AppendLine("                {");

        foreach (var property in type.Properties)
        {
            EmitAccessor(builder, type.FullyQualifiedName, property);
        }

        builder.AppendLine("                });");
    }

    private static string RegistrarName(string rootTypeFullyQualifiedName)
    {
        var builder = new StringBuilder(rootTypeFullyQualifiedName.Length);

        foreach (var character in rootTypeFullyQualifiedName)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.Append("_Registrar").ToString();
    }
}
